import Head from "next/head";
import Navbar from "@/components/navbar";
import styled from "styled-components";
import Products from "@/components/products";

const Content = styled.div`
  background: var(--background);
  color: var(--text);
`;
export default function Home() {
  return (
    <>
      <Head>
        <title>BUY IT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Content className="flex flex-col w-full">
          <Navbar />
          <Products />
          <Products />
        </Content>
      </main>
    </>
  );
}
